dist: trusty
language: cpp
compiler:
 - g++-5
 - clang++
sudo: false
os:
 - linux
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - nialldouglas14@gmail.com

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - clang-3.3
    - cmake
    - cmake-data

script:
 - if [ "$CXX" = "g++" ]; then export CXX=g++-5; fi;
# - if [ "$CXX" = "clang++" ]; then export CXX=clang++-3.3; fi;
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_BUILD_TYPE=Release
 - cmake --build .
 - bin/test-status-code
 -
   if [ "$CXX" = "g++" ]; then
     cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=undefined" -DCMAKE_EXE_LINKER_FLAGS=-fsanitize=undefined;
     cmake --build .;
     bin/test-status-code;
   fi
 
after_success:

after_failure:
