# version format
version: 0.80.{build}-{branch}
 
# branches to build
branches:
  only:
    - master
skip_tags: true
 
image: Visual Studio 2017
init:
  - git config --global core.longpaths true

clone_folder: c:\status-code
platform: x64 
configuration: Release

before_build:
build_script:
 - mkdir build
 - cd build
 - cmake .. -G"Visual Studio 15 2017 Win64"
 - cmake --build . --config Release
after_build:

before_test:
test_script:
 - bin\Release\test-status-code
after_test:

on_success:
on_failure:
on_finish:
